// config.bin - 12:27:02 06/11/13, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class GNT_C185 {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
	};
};

class CfgMagazines {
	class 14Rnd_FFAR;	// External class reference
	
	class 12Rnd_FFAR : 14Rnd_FFAR {
		count = 12;
	};
};

class CfgWeapons {
	class FFARLauncher;	// External class reference
	
	class FFARLauncher_12 : FFARLauncher {
		magazines[] = {"12Rnd_FFAR"};
	};
};

class CfgVehicles {
	class Plane;	// External class reference
	class Ship;	// External class reference
	class Strategic;	// External class reference
	class PlaneWreck;	// External class reference
	
	class GNT_C185wreck : PlaneWreck {
		scope = 1;
		
		class Armory {
			disabled = 1;
		};
		model = "\GNT_C185\GNT_C185wreck.p3d";
		typicalCargo[] = {};
		irTarget = 0;
		transportAmmo = 0;
		transportRepair = 0;
		transportFuel = 0;
		transportSoldier = 4;
		
		class Eventhandlers {};
	};
	
	class GNTXPlaneC2 : Plane {
		class NewTurret;	// External class reference
		class AnimationSources;	// External class reference
	};
	
	class GNTXFloat : Strategic {
		scope = 1;
		animated = 0;
		vehicleClass = "training";
		typicalCargo[] = {};
		irTarget = 0;
		mapSize = 1;
		model = "\GNT_C185\Float.p3d";
		icon = "";
		displayName = "fake float";
		accuracy = 0.1;
		camouflage = 0.1;
		transportAmmo = 0;
		transportRepair = 0;
		transportFuel = 0;
		destrType = "DestructTent";
		coefInside = 0.5;
		coefInsideHeur = 0.8;
		cost = 0;
		armor = 5000;
	};
	
	class GNTXFloat1 : GNTXFloat {
		model = "\GNT_C185\Float1.p3d";
	};
	
	class GNTXFloat2 : Ship {
		scope = 1;
		faction = CIV;
		side = 3;
		displayName = "Cessna 185 Float";
		accuracy = 0.1;
		camouflage = 0.1;
		fuelCapacity = 90;
		armor = 5000;
		cost = 100;
		irTarget = 0;
		hideUnitInfo = 1;
		model = "\GNT_C185\Float2.p3d";
		icon = "";
		hasGunner = 0;
		hasDriver = 0;
	};
	
	class GNT_C185 : GNTXPlaneC2 {
		scope = 2;
		canFloat = 1;
		model = "\GNT_C185\GNT_C185";
		displayName = "Cessna 185 Skywagon";
		side = 3;
		faction = CIV;
		transportSoldier = 3;
		crew = "Pilot";
		driverAction = "AN2_Cargo_EP1";
		cargoAction[] = {"AN2_Cargo_EP1", "KA52_Pilot", "KA52_Pilot"};
		getInAction = "GetInLow";
		getOutAction = "GetOutLow";
		cargoGetInAction[] = {"GetOutLow"};
		cargoGetOutAction[] = {"GetOutLow"};
		Icon = "\GNT_C185\C185Icon.paa";
		picture = "\GNT_C185\C185Pic.paa";
		accuracy = 0.3;
		gearRetracting = 0;
		nameSound = "plane";
		damageEffect = "DamageSmokePlane";
		destrType = "DestructWreck";
		
		class Damage {
			tex[] = {};
			mat[] = {"GNT_C185\tex\c185F.rvmat", "GNT_C185\tex\c185F_damage.rvmat", "GNT_C185\tex\c185F_destruct.rvmat", "GNT_C185\tex\c185W.rvmat", "GNT_C185\tex\c185W_damage.rvmat", "GNT_C185\tex\c185W_destruct.rvmat", "GNT_C185\tex\c185.rvmat", "GNT_C185\tex\c185_damage.rvmat", "GNT_C185\tex\c185_destruct.rvmat"};
		};
		soundEngine[] = {"\GNT_C185\engine.wav", 5.62341, 1.0};
		soundEnviron[] = {"\ca\sounds\air\mv22\int-wind1", 0.1, 1.0};
		insideSoundCoef = 0.6;
		landingSpeed = 120;
		maxSpeed = 250;
		armor = 20;
		ejectSpeed[] = {0, 0, -0.6};
		flapsFrictionCoef = 3.5;
		wheelSteeringSensitivity = 0.7;
		cost = 20000;
		type = "VAir";
		threat[] = {0.1, 1, 0.7};
		aileronSensitivity = 0.5;
		elevatorSensitivity = 0.09;
		noseDownCoef = 2.01;
		landingAoa = 7*3.1415/180;
		envelope[] = {0, 0.2, 0.9, 2.1, 2.5, 3.3, 3.5, 3.5, 3.5, 3.0, 2.5, 2.0};
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse2.paa", "\gnt_c185\tex\c185wings2.paa", "\gnt_c185\tex\c185misc.paa", ""};
		
		class AnimationSources : AnimationSources {
			class MvA1 {
				source = "user";
				animPeriod = 0.1;
				initPhase = 0;
			};
			
			class MvA2 {
				source = "user";
				animPeriod = 2.0;
				initPhase = 0;
			};
			
			class RPod {
				source = "user";
				animPeriod = 0.01;
				initPhase = 0;
			};
		};
		extCameraPosition[] = {0, 4, -15};
		irTarget = 1;
		irScanRange = 2000;
		irScanGround = 1;
		weapons[] = {};
		magazines[] = {};
		
		class EventHandlers {
			init = "_sxr = _this execvm ""\GNT_C185\scr\C185Init.sqf"";_scr = _this execVM ""\ca\Data\ParticleEffects\SCRIPTS\init.sqf"";";
			engine = "_this execVM ""\GNT_C185\scr\C185_Exhaust.sqf"";[_this select 0] execvm ""\GNT_C185\scr\G_CheckEngine.sqf"";";
			killed = "_this call BIS_Effects_EH_Killed;";
		};
	};
	
	class GNT_C185F : GNT_C185 {
		scope = 2;
		model = "\GNT_C185\GNT_C185F";
		displayName = "Cessna 185 Amphibian";
		wheelSteeringSensitivity = 0.5;
		getInAction = "GetInMedium";
		getOutAction = "GetOutMedium";
		cargoGetInAction[] = {"GetInMedium"};
		cargoGetOutAction[] = {"GetOutMedium"};
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse4.paa", "\gnt_c185\tex\c185wings4.paa", "\gnt_c185\tex\c185misc.paa", ""};
		
		class EventHandlers {
			init = "_sxr = _this execvm ""\GNT_C185\scr\C185FInit.sqf"";_scr = _this execVM ""\ca\Data\ParticleEffects\SCRIPTS\init.sqf"";";
			engine = "_this execVM ""\GNT_C185\scr\C185F_Exhaust.sqf"";[_this select 0] execvm ""\GNT_C185\scr\G_CheckEngine.sqf"";";
			killed = "_this call BIS_Effects_EH_Killed;";
		};
	};
	
	class GNT_C185R : GNT_C185 {
		faction = CIV_RU;
		crew = "RU_Pilot";
		typicalCargo[] = {"RU_Pilot"};
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse3.paa", "\gnt_c185\tex\c185wings3.paa", "\gnt_c185\tex\c185misc.paa", ""};
	};
	
	class GNT_C185E : GNT_C185F {
		faction = CIV_RU;
		crew = "RU_Pilot";
		typicalCargo[] = {"RU_Pilot"};
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse3.paa", "\gnt_c185\tex\c185wings3.paa", "\gnt_c185\tex\c185misc.paa", ""};
	};
	
	class GNT_C185C : GNT_C185 {
		faction = BIS_TK_CIV;
		crew = "TK_CIV_Takistani01_EP1";
		typicalCargo[] = {"TK_CIV_Takistani01_EP1"};
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse5.paa", "\gnt_c185\tex\c185wings5.paa", "\gnt_c185\tex\c185misc.paa", ""};
	};
	
	class GNT_C185T : GNT_C185 {
		side = 0;
		faction = BIS_TK;
		crew = "TK_Soldier_Pilot_EP1";
		typicalCargo[] = {"TK_Soldier_Pilot_EP1"};
		displayName = "Cessna 185 Armed";
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse6.paa", "\gnt_c185\tex\c185wings6.paa", "\gnt_c185\tex\c185misc.paa", "\gnt_c185\tex\c185wings6.paa"};
		weapons[] = {"FFARLauncher_12"};
		magazines[] = {"12Rnd_FFAR"};
		aileronSensitivity = 0.4;
	};
	
	class GNT_C185U : GNT_C185 {
		side = 0;
		faction = BIS_TK;
		crew = "TK_Soldier_Pilot_EP1";
		typicalCargo[] = {"TK_Soldier_Pilot_EP1"};
		displayName = "Cessna 185 Recon";
		hiddenselections[] = {"texFuse", "texWing", "texMisc", "RPod"};
		hiddenSelectionsTextures[] = {"\gnt_c185\tex\c185fuse6.paa", "\gnt_c185\tex\c185wings6.paa", "\gnt_c185\tex\c185misc.paa", ""};
	};
};
