class Ka137_DZ: Ka137_PMC	{
		displayname = "Ka137 Mini-Heli";
		displaynameshort = "Ka137";
		scope = 2;
		side = 2;
		crew = "";
		radartype = 0;
		typicalCargo[] = {};
		hiddenSelections[] = {};
		class TransportMagazines{};
		class TransportWeapons{};
		weapons[] = {};
		magazines[] = {};
		gunnerHasFlares = false;
		commanderCanSee = 2+16+32;
		gunnerCanSee = 2+16+32;
		driverCanSee = 2+16+32;
		transportMaxWeapons = 1;
		transportMaxMagazines = 10;
		transportmaxbackpacks = 1;
	};